### ISSUE TITLE
Better naming conventions

### ISSUE THREAD

**Issue by Weestuarty** [GlazedBelmont/es-de-android-custom-systems#1]
To make things better visually rename the apps system to android as its themed already.
Also you could add the emulators system also and use the same setup as apps. I have it setup so i can confirm it works

**Comment by GlazedBelmont** [comment]
Renamed it to android in https://github.com/GlazedBelmont/es-de-android-custom-systems/commit/c0ddf2e5d0b83ed08322a3b3e61a9300dc79a5b0

I'm a bit confused what you mean by emulators system, does it reference an `emulators` folder or are you manually filtering out stuff?

**Comment by Weestuarty** [comment]
emulators is a "system" that exists on other versions of esde where you can put shortcuts to launch emulators without games for config etc. if you add a system in your file exact same as apps but replacing apps with emulators. you can then save or just move those emulator .app files into an "emulators" folder. Every official theme has support for this "system"

<system>
        <name>emulators</name>
        <fullname>Emulators</fullname>
        <path>%ROMPATH%/emulators</path>
        <extension>.app</extension>
        <command label="ES Applauncher">%EMULATOR_APPS% %EXTRA_GamePath%=%ROM%</command>
        <platform>android</platform>
        <theme>emulators</theme>
    </system>

**Comment by GlazedBelmont** [comment]
ah I see, thanks for the precision

**Comment by Weestuarty** [comment]
Itll just help people thin out android apps and keep things themed.
