### ISSUE TITLE
Add support for Suyu for Android 9

### ISSUE THREAD

**Issue by Tailsproxy** [GlazedBelmont/es-de-android-custom-systems#15]
I had some issues getting XforYouX's build of Suyu for Android 9 working with this as it calls on a different activity to the mainline Suyu, i.e,"dev.suyu.suyu_emu/dev.suyu.suyu_emu.activities.EmulationActivity" . Might be worth adding this as a player in the XML as it's one of the few builds that work with Android 10 devices like the Odin Pro.

**Comment by GlazedBelmont** [comment]
https://github.com/GlazedBelmont/es-de-android-custom-systems/commit/07a43af988fcc0b9b6a68c642e3798803df74b01
