### ISSUE TITLE
ES-DE still wants to open Skyline

### ISSUE THREAD

**Issue by vmatkov** [GlazedBelmont/es-de-android-custom-systems#16]
I am on ES-DE Version 3.0.3-26. I have the ES-DE installed on my internal drive of my Odin 2 Pro. So I have manually created a folder 'custom_systems' and copied the files into the folder. When I try to start up a game, I get the message "ERROR: COULDN'T FIND EMULATOR 'SKYLINE', HAS IT BEEN PROPERLY INSTALLED?"

**Comment by RobZombie9043** [comment]
Go to main menu > other settings > alternative emulator > switch and choose a different emulator
