### ISSUE TITLE
Add Mandarine as an alternate 3Ds emulator

### ISSUE THREAD

**Issue by dburr** [GlazedBelmont/es-de-android-custom-systems#17]
[Mandarine](https://github.com/mandarine3ds/mandarine) is a new fork of Citra that claims better performance than stock Citra. It would be nice if it could be added as an alternative emulator for launching 3Ds games. I took a brief look through the xml files in EmulationStation and am not exactly sure where to start. I recently suffered a badly broken ES-DE install; managed to get everything back to normal, but I am a bit hesitant to start poking at random XML files. :)

**Comment by GlazedBelmont** [comment]
Been watching it for a release and yeah will add it at some point

**Comment by egorbunovs** [comment]
While waiting for the update - you can add the config yourself.
Add the following to the `es_find_rules.xml`:
```xml
    <emulator name="MANDARINE">
        <!-- Nintendo 3DS emulator Mandarine -->
        <rule type="androidpackage">
            <entry>io.github.mandarine3ds.mandarine/io.github.mandarine3ds.mandarine.activities.EmulationActivity</entry>
        </rule>
    </emulator>	
```
And the following to the `es_systems.xml` under `n3ds` just bellow the `Panda3DS` entry:
```xml
<command label="Mandarine (Standalone)">%EMULATOR_MANDARINE% %ACTIVITY_CLEAR_TASK% %ACTIVITY_CLEAR_TOP% %DATA%=%ROMSAF%</command>
```

**Comment by GlazedBelmont** [comment]
https://github.com/GlazedBelmont/es-de-android-custom-systems/commit/839a495238316cc4662b34b8b7ae5496fc27bd7a

merged @egorbunovs's workaround, sorry for the wait, I legit have not touched a retro handheld in a bit
