### ISSUE TITLE
Can you add a uzuy edge and uzuy mmjr

### ISSUE THREAD

**Issue by angel68xp** [GlazedBelmont/es-de-android-custom-systems#19]
Can you  please add them? They are switch emulator that’s still being updated

**Comment by RobZombie9043** [comment]
Added uzuy x which seems to be the latest name for this. Although I’m sure it will be something else next week ¯\_(ツ)_/¯

**Comment by angel68xp** [comment]
Thank you, but now I’m getting an error when I add  new xml saying some type of error with switch simulator

**Comment by RobZombie9043** [comment]
Go into alternative emulators and change the emulator selected.

**Comment by angel68xp** [comment]
Only skyline showing up

**Comment by RobZombie9043** [comment]
Then the custom system XMLs are not being loaded by ES-DE. 

Download using the green code button on the main page to make sure you have downloaded properly as xml. Then unzip the 2 xml files and add to ~ES-DE/custom_systems. Fully restart ES-DE.

If still not working check the log file in ~ES-DE/logs and see if there is an error related to loading the custom systems.

**Comment by angel68xp** [comment]
OK, it’s working. It was adding one before XML. That’s why I wasn’t working.
