### ISSUE TITLE
Is it possible to add the new CEMU android emu?

### ISSUE THREAD

**Issue by azurite2** [GlazedBelmont/es-de-android-custom-systems#21]
title

**Comment by GlazedBelmont** [comment]
I'm not certain if wiiu games can be launched from frontends with CEMU just yet, perhaps @RobZombie9043 can confirm.

**Comment by RobZombie9043** [comment]
Yep don't think it supports it yet. When it does Leon will add support for it to ES-DE.

**Comment by RobZombie9043** [comment]
Added with https://github.com/GlazedBelmont/es-de-android-custom-systems/pull/22

Make sure you have the latest build of cemu for frontend support to work.
