### ISSUE TITLE
Is possible to add Ziunx?

### ISSUE THREAD

**Issue by mrz4697** [GlazedBelmont/es-de-android-custom-systems#23]
I tried to do it myself by adding the following entries:

es_systems.xml entry:

<command label="Ziunx (Standalone)">%EMULATOR_Ziunx% %ACTION%=android.intent.action.VIEW %DATA%=%ROMPROVIDER%</command>

I added this to the list of switch emulators. I was unsure whether to have it set to "android.intent.action.VIEW" or "android.nfc.action.TECH_DISCOVERED" as I don't know the difference.

es_find_rules.xml entry:

<emulator name="ZIUNX">
	    
	    <rule type="androidpackage">
	        <entry>org.Ziunx.Ziunx_emu.ea/org.yuzu.yuzu_emu.activities.EmulationActivity</entry>
	    </rule>
    </emulator>

I copy pasted from the other emulators and went into "android/data" to determine that the folder was "org.Ziunx.Ziunx_emu.ea".
I then used automate to find the activity "org.yuzu.yuzu_emu.activities.EmulationActivity"

It appears in es-de but launching a game gives the following error:

ERROR: MISSING EMULATOR FIND RULES CONFIGURATION FOR 'Ziunx'

Sorry for long issue, hope you can help

**Comment by mrz4697** [comment]
Issue resolved 
emulator name="Ziunx"
Ziunx in the previous line was mistakenly written with all caps. I did this to copy all the other emulators but that was a mistake. I now seen to be getting "not bootable game" error but that seems to be aziunx error (I keep needing to reinput the prod.keys.

**Comment by RobZombie9043** [comment]
Added Ziunx one
