### ISSUE TITLE
Ryujinx as alternate Switch emulator in ES-DE

### ISSUE THREAD

**Issue by cbrucealleyne** [GlazedBelmont/es-de-android-custom-systems#27]
I am trying to add Ryujinx as an alternate Switch emulator. I have found one game (FIFA) that only runs properly in this emulator. Ant support would be appreciated.

**Comment by RobZombie9043** [comment]
Ask the devs to add frontend support ;)

**Comment by GlazedBelmont** [comment]
If it ever gets continued and gets frontend support, we'll add it but right now, it's just very unlikely to ever happen.
