### ISSUE TITLE
Create releases to monitor changes

### ISSUE THREAD

**Issue by jorgevillalta** [GlazedBelmont/es-de-android-custom-systems#29]
I like your script, honestly, but imo will be better if you create releases to track/monitor it with apps like [Obtanium ](https://obtainium.imranr.dev/)or similar. I know, is a little bit of work by your side, but maybe this can help others to use it easily. Thx in avance.

**Comment by GlazedBelmont** [comment]
Yeah that's fair, can definitely be done.

@RobZombie9043 Thoughts? Changes are sparser nowadays (~1 every 3-7 days) so pushing a release with every x days with the changelog of each one would be good for people using updaters like that.

**Comment by RobZombie9043** [comment]
Easy enough. First one done - [v1.0](https://github.com/GlazedBelmont/es-de-android-custom-systems/releases/tag/v1.0)

**Comment by RobZombie9043** [comment]
![Screenshot_20250101-080227](https://github.com/user-attachments/assets/297c31dc-b372-4570-b7be-427e53175f78)

**Comment by GlazedBelmont** [comment]
In addition, I've added a button to easily add them to Obtainium in the README

**Comment by jorgevillalta** [comment]
As a developer I appreciate your work, thx very much guys.
