### ISSUE TITLE
Added Suyu emulator

### ISSUE THREAD

**Issue by hallstudios** [GlazedBelmont/es-de-android-custom-systems#3]
Hi there.  I actually downloaded this repo to add in Suyu support (as its now had an official Android build, and works fine), but then realised I cannot check back the changes.

I didn't want to create my own fork as your wonderful project would then become too fragmented, so just thought I would mention it here, and wondered if you wanted to add in Suyu support?

**Comment by hallstudios** [comment]
Actually, I did just create a fork, and added my changes, so it should be available in a Pull Request if you wanted.

**Comment by GlazedBelmont** [comment]
https://github.com/GlazedBelmont/es-de-android-custom-systems/commit/4af917d4e80510edd259d463506b176c41cdabd1
