### ISSUE TITLE
Would it be possible to add SNES MSU-1 and MSU-MD?

### ISSUE THREAD

**Issue by SuperBadger77** [GlazedBelmont/es-de-android-custom-systems#7]
As the title suggests - could you create entries for SNES MSU-1 and MSU-MD?

**Comment by GlazedBelmont** [comment]
Hello, I try to keep parity with Art-Boot-Next so I'm currently checking with the theme creator to add these into his theme.
https://discord.com/channels/857266429275144222/979298216656928828/1237067352164667583

**Comment by GlazedBelmont** [comment]
It just got added, I'll go work on it this afternoon

**Comment by GlazedBelmont** [comment]
https://github.com/GlazedBelmont/es-de-android-custom-systems/commit/39c2268aee3199be42f1bf1beb048671d3afdd45
